# Generated by Django 4.2 on 2023-10-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
